name: Code Review

on:
  pull_request:
    branches:
      - main

env:
  GIT_PAT: ${{ secrets.GIT_PAT }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node with npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Download dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
      - name: Run ESLint
        run: npm run lint
      - name: Run build
        run: npm run build
