name: Code Coverage Reporter

on:
  pull_request:
    branches:
      - main

env:
  GIT_PAT: ${{ secrets.GIT_PAT }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  coverage:
    name: Get Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node with npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Download dependencies
        run: npm ci
      - name: Run Jest
        run: npm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
